version: '3.7'

services:
    server-php:
        container_name: server-php
        hostname: server-php
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - server-network
        depends_on:
            - server-postgres

    server-nginx:
        image: nginx:1.23.1-alpine
        container_name: server-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - server-network
        depends_on:
            - server-php

    server-postgres:
        image: postgres:14.4-alpine
        container_name: server-postgres
        restart: unless-stopped
        ports:
            - "5434:5432"
        networks:
            - server-network
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: test
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        hostname: postgres

networks:
    server-network:
        driver: bridge
